//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int Id { get; set; }
        public string Imagem { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public Nullable<System.DateTime> Expiracao { get; set; }
        public string Telefone { get; set; }
        public string Link { get; set; }
        public Nullable<System.DateTime> Cadastro { get; set; }
        public Nullable<int> Contador { get; set; }
    }
}
