//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteCertificado
    {
        public string Id { get; set; }
        public int IdCliente { get; set; }
        public int IdCertificado { get; set; }
        public string Descricao { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
    
        public virtual Certificado Certificado { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
