//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Associado> Associado { get; set; }
        public virtual DbSet<AssociadoPagamento> AssociadoPagamento { get; set; }
        public virtual DbSet<Banner> Banner { get; set; }
        public virtual DbSet<Certificado> Certificado { get; set; }
        public virtual DbSet<Disponibilidade> Disponibilidade { get; set; }
        public virtual DbSet<Equipamento> Equipamento { get; set; }
        public virtual DbSet<Plano> Plano { get; set; }
        public virtual DbSet<Profissao> Profissao { get; set; }
        public virtual DbSet<Profissional> Profissional { get; set; }
        public virtual DbSet<ProfissionalCertificado> ProfissionalCertificado { get; set; }
        public virtual DbSet<ProfissionalEquipamentos> ProfissionalEquipamentos { get; set; }
        public virtual DbSet<ProfissionalExperiencia> ProfissionalExperiencia { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
