//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagamento
    {
        public int Id { get; set; }
        public int IdCliente { get; set; }
        public int IdPlano { get; set; }
        public decimal Valor { get; set; }
        public int Dias { get; set; }
        public string Descricao { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public int Situacao { get; set; }
        public string CheckoutIdentifier { get; set; }
        public Nullable<System.DateTime> DataConfirmacao { get; set; }
        public Nullable<int> IdServicoContabil { get; set; }
        public Nullable<int> IdBanner { get; set; }
        public int Vezes { get; set; }
        public string Url { get; set; }
        public string TipoPlano { get; set; }
        public string BeneficioAplicado { get; set; }
    
        public virtual Banner Banner { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Plano Plano { get; set; }
        public virtual ServicoContabil ServicoContabil { get; set; }
    }
}
