//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParceiroPagamento
    {
        public int Id { get; set; }
        public int IdParceiro { get; set; }
        public int IdPlano { get; set; }
        public decimal Valor { get; set; }
        public int Dias { get; set; }
        public string Descricao { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public int Situacao { get; set; }
        public string CheckoutIdentifier { get; set; }
        public Nullable<System.DateTime> DataConfirmacao { get; set; }
    
        public virtual Parceiro Parceiro { get; set; }
        public virtual Plano Plano { get; set; }
    }
}
