//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfissionalCertificado
    {
        public int Id { get; set; }
        public int IdProfissional { get; set; }
        public int IdCertificado { get; set; }
        public bool FlagPrincipal { get; set; }
    
        public virtual Certificado Certificado { get; set; }
        public virtual Profissional Profissional { get; set; }
    }
}
