//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfissionalFotos
    {
        public int Id { get; set; }
        public string Imagem { get; set; }
        public System.DateTime Cadastro { get; set; }
        public int IdProfissional { get; set; }
    
        public virtual ClienteProfissional ClienteProfissional { get; set; }
    }
}
